apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'email-notice'
      group_by: ['alertname', 'Service', 'Stage', 'Role']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    receivers:
    - name: 'email-notice'
      email_configs:
      - to: 'tuemail@gmail.com'
        from: 'tuemail@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'tuemail@gmail.com'
        auth_password: 'password usa token de cooreo en caso de google'
        send_resolved: true

