apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
  labels:
    app: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-exporter-service
  labels:
    app: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  ports:
    - protocol: TCP
      port: 9253
      targetPort: 9253
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  labels:
    app: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
