apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: openldap-container
        image: osixia/openldap:latest
        ports:
        - containerPort: 389
        env:
        - name: LDAP_ORGANISATION
          value: "proyectoalex"
        - name: LDAP_DOMAIN
          value: "proyectoalex.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "secret"
        - name: LDAP_CONFIG_PASSWORD
          value: "secret2"
        - name: LDAP_READONLY_USER_PASSWORD
          value: "secret3"
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: node-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-node-exporter-service
  labels:
    app: ldap
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
