apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
      name: metrics
  type: ClusterIP