apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: alejandro
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_USER
          value: exporter
        - name: MYSQL_exporter_PASSWORD
          value: exporter
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      - name: mysqld-exporter
        image: prom/mysqld-exporter:latest
        args:
        - "--config.my-cnf=/etc/.mysqld_exporter.cnf"
        - "--collect.global_status"
        - "--collect.info_schema.innodb_metrics"
        - "--collect.auto_increment.columns"
        - "--collect.info_schema.processlist"
        - "--collect.binlog_size"
        - "--collect.info_schema.tablestats"
        - "--collect.global_variables"
        - "--collect.info_schema.query_response_time"
        - "--collect.info_schema.userstats"
        - "--collect.info_schema.tables"
        - "--collect.perf_schema.tablelocks"
        - "--collect.perf_schema.file_events"
        - "--collect.perf_schema.eventswaits"
        - "--collect.perf_schema.indexiowaits"
        - "--collect.perf_schema.tableiowaits"
        - "--collect.slave_status"
        ports:
        - containerPort: 9104
          name: mysqld-metrics
        volumeMounts:
        - name: mysqld-exporter-config
          mountPath: /etc/.mysqld_exporter.cnf
          subPath: .mysqld_exporter.cnf
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: node-metrics
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysqld-exporter-config
        configMap:
          name: mysqld-exporter-config
      restartPolicy: Always
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-exporter-config
data:
  .mysqld_exporter.cnf: |
    [client]
    user=exporter
    password=exporter