apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  smtp-auth-password: d3pkeSBka2FvIGt6bmsgY3ZybAo=
  ldap-admin-password: c2VjcmV0Cg==
  ldap-config-password: c2VjcmV0Cg==
  ldap-readonly-password: c2VjcmV0Cg==
  mysql-root-password: c2VjcmV0Cg==